### ISSUE TITLE
Newsletter form - no consent?

### ISSUE THREAD

**Issue by turowicz** [privacyradius/gdpr-checklist#10]
![image](https://user-images.githubusercontent.com/1055391/39857349-49f1edba-5433-11e8-8b61-0430537ddaf4.png)

**Comment by Gdewilde** [comment]
OMG, will get that fixed 😅

**Comment by Gdewilde** [comment]
Thanks for noticing. The new form can be found here: https://privacyradius.us18.list-manage.com/subscribe
